### PR TITLE
limit number of supported BCC versions

### PR DESCRIPTION
**Pull request by brayniac**
As mentioned in #87 CI is not currently running for anything pre
0.10.0 even though 0.5.0 and up are allowed in the manifest. To
reduce the number of combinations for testing and development
efforts, we should have a policy around the number of supported BCC
versions.

In this change, we reduce the supported BCC versions to the most
recent 3 minor versions supported by the Rust BCC crate. To keep
the combinations contained, we will only support the most recent
patch release for a given minor release. For example, if 0.12.1
were to be released, we would drop support for 0.12.0 but continue
to support 0.10.0 and 0.11.0

As per #87, this will still allow Ubuntu, Arch, and Fedora users to
install BCC from packages (either distro or iovisor provided).

### CODE REVIEW

**Comment by WesleyAC** [comment]
this sounds reasonable to me. it does seem like a fairly aggressive policy (0.10.0 was released less than a year ago, it seems?), but you're more familiar with the pace of bcc development than i am, maybe that's a reasonable cadence. if the api is stable enough that supporting one old release should result in releases newer than that being supported as well, it might be reasonable to choose one older version as well as the two most recent, so we can be more thoughtful about when we bump the required API version?

but i also think that we don't need to do that, just supporting the most recent three major versions also seems fine.

thoughts?

**Comment by brayniac** [comment]
It might be aggressive. 0.13.0 is out, which would put us as supporting 0.11.0-0.13.0 - which is only from Oct 2019 -> Present. The release cadence is pretty sporadic and isn't always breaking - so it's difficult to estimate the development burden. I just would like a clear way to determine what versions we support.

I initially picked most recent 3, because that's what we have in the CI matrix currently.

My other thought is to support the oldest version out of Debian Stable and CentOS 7 - which does offer some better distro coverage. Currently, that version is 0.8.0 which is from 2019.01.11. That's probably a more reasonable target for backward compatibility without taking on too much cost in terms of CI build times and development/maintenance efforts.

**Comment by WesleyAC** [comment]
running 0.8.0 + the most recent two versions in CI seems to me like a reasonable compromise between backwards compat and having quick CI builds

**Comment by brayniac** [comment]
> running 0.8.0 + the most recent two versions in CI seems to me like a reasonable compromise between backwards compat and having quick CI builds

Let's see what the build time works out to be with the latest diff. The builds for this project are already pretty long. I'm not sure the policy complexity is worth the time savings in CI to drop versions in the middle of the range.

**Comment by brayniac** [comment]
CI runtime seemed reasonable relative to before this change. Will proceed to merge

**Pull request merged**
